### ISSUE TITLE
switch to streamlink 2.0

### ISSUE THREAD

**Issue by christianWilling** [lauwarm/docker-streamlink-recorder#10]
streamlink 1.7 is broken on twitch accordding to https://github.com/streamlink/streamlink/issues/3488

**Comment by lauwarm** [comment]
Thanks for letting me know.

The Branch `python3.9.0_buster_2.0.0` is updated to streamlink 2.0.0.

**Comment by christianWilling** [comment]
thanks im using python3.9.0_buster_2.0.0 for now
