### ISSUE TITLE
error: Unable to open URL: https://gql.twitch.tv/gql

### ISSUE THREAD

**Issue by Marc3l1988** [lauwarm/docker-streamlink-recorder#102]
Yesterday i wanted to record a stream but the logs says this:

[cli][info] Found matching plugin twitch for URL twitch.tv/sweeettails

error: No playable streams found on this URL: twitch.tv/sweeettails

[cli][info] Found matching plugin twitch for URL twitch.tv/sweeettails

error: Unable to open URL: https://gql.twitch.tv/gql (HTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fa4a6022540>: Failed to resolve 'gql.twitch.tv' ([Errno -3] Temporary failure in name resolution)")))

[cli][info] Found matching plugin twitch for URL twitch.tv/sweeettails

error: Unable to open URL: https://gql.twitch.tv/gql (HTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f1d40a41130>: Failed to resolve 'gql.twitch.tv' ([Errno -3] Temporary failure in name resolution)")))

[cli][info] Found matching plugin twitch for URL twitch.tv/sweeettails

error: Unable to open URL: https://gql.twitch.tv/gql (HTTPSConnectionPool(host='gql.twitch.tv', port=443): Max retries exceeded with url: /gql (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f7660771130>: Failed to resolve 'gql.twitch.tv' ([Errno -3] Temporary failure in name resolution)")))

[cli][info] Found matching plugin twitch for URL twitch.tv/sweeettails

error: No playable streams found on this URL: twitch.tv/sweeettails

**Comment by lauwarm** [comment]
Hey @Marc3l1988,

I tried to record this stream and don't get this "unable to open URL" error.

It looks like this at my end:
```
UID : 501 
GID : 20
[cli][info] Found matching plugin twitch for URL twitch.tv/sweeettails
error: No playable streams found on this URL: twitch.tv/sweeettails
[cli][info] Found matching plugin twitch for URL twitch.tv/sweeettails
error: No playable streams found on this URL: twitch.tv/sweeettails
[cli][info] Found matching plugin twitch for URL twitch.tv/sweeettails
error: No playable streams found on this URL: twitch.tv/sweeettails
[cli][info] Found matching plugin twitch for URL twitch.tv/sweeettails
error: No playable streams found on this URL: twitch.tv/sweeettails
[cli][info] Found matching plugin twitch for URL twitch.tv/sweeettails
error: No playable streams found on this URL: twitch.tv/sweeettails
[cli][info] Found matching plugin twitch for URL twitch.tv/sweeettails
error: No playable streams found on this URL: twitch.tv/sweeettails
[cli][info] Found matching plugin twitch for URL twitch.tv/sweeettails
error: No playable streams found on this URL: twitch.tv/sweeettails
```

Maybe there is a problem with DNS resolution at your end? 
```
([Errno -3] Temporary failure in name resolution)
```

**Comment by Marc3l1988** [comment]
@lauwarm 

That is what i'm seeing now also. But the error that i gave in the first post occours when there is a active stream.
Since then there where 2 more streams and they recorderd perfectly.
