### ISSUE TITLE
Issue with chaturbate plugin after update

### ISSUE THREAD

**Issue by Nach0-Stallion** [lauwarm/docker-streamlink-recorder#12]
Hi again.
look, i know both times ive messaged is because of this plugin.. im sorry :)
I moved recently and got my server back up and running today and found a whole bunch of errors for any docker using this plugin (twitch is fine) after you helped me last time get it running its been solid so i hope you can help again!
or can i force it to use the old docker release?

I havent changed anything from when you told me to use "--plugin-dirs=/home/plugins/" in the streamOptions setting
Any help greatly appreciated..

`[session][error] Failed to load plugin chaturbate from /home/plugins/
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/streamlink-2.0.0-py3.9.egg/streamlink/session.py", line 423, in load_plugins
mod = load_module(module_name, path)
File "/usr/local/lib/python3.9/site-packages/streamlink-2.0.0-py3.9.egg/streamlink/utils/__init__.py", line 25, in load_module
spec.loader.exec_module(mod)
File "<frozen importlib._bootstrap_external>", line 790, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/home/plugins/chaturbate.py", line 5, in <module>
from streamlink.plugin.api import http
ImportError: cannot import name 'http' from 'streamlink.plugin.api' (/usr/local/lib/python3.9/site-packages/streamlink-2.0.0-py3.9.egg/streamlink/plugin/api/__init__.py)
[cli][info] streamlink is running as root! Be careful!
error: No plugin can handle URL: www.chaturbate.com/editedforprivacyusername`

**Comment by lauwarm** [comment]
Hey,

I encountered that Problem too. With the same Session Error log as you posted.
Seems that streamlink with Version 2.0.0 changed plugin.api.

Also note that streamlink itself stopped supporting nsfw plugins in total. So those plugins won't get any updates soon I guess. 
https://github.com/streamlink/streamlink/pull/1838#issuecomment-459184294 elaborates about this more.

For the time being the best solution will be to use an older version.
With docker itself you can specify a Tag.
 
```
$ docker run -v /home/:/home/download -e streamLink='twitch.tv/twitch' -e streamQuality='best' -e streamName='twitch' -e streamOptions='--twitch-disable-hosting' lauwarm/streamlink-recorder:python3.9.0_buster_1.7
```

This Version does not support UID and GID tho. Keep that in mind.

**Comment by Nach0-Stallion** [comment]
Thank you for the quick reply, yeah the new version doesn't seem to support it, so i managed to force the old version, thank you for the tip!, ive also worked out how to install the userID version for the twitch streamers.. they aren't on yet but it shows no errors and seems ready to go!. thank you again!

**Comment by lauwarm** [comment]
Alright,

I've updated the Branch `python3.9.0_buster_1.7`. It now uses UserID and GroupID. Streamlink should not be running as root anymore.

As this Image is using streamlink 1.7 it should also work with some old/legacy Plugins. But there is no guarantee that it will be working in the future, as I am not maintaining the Plugins itself.
