### ISSUE TITLE
Update Streamlink

### ISSUE THREAD

**Issue by MadZeh** [lauwarm/docker-streamlink-recorder#17]
Would you be so kind and update to streamlink 2.4.0? This would be very nice.

**Comment by MadZeh** [comment]
Me again. Still have your Container in use. But would you be so kind again and update to streamlink to the latest version?

**Comment by lauwarm** [comment]
Hey @MadZeh,

Thanks for letting me know. I just updated the Image to `streamlink 3.2.0`.
