### ISSUE TITLE
Platform maybe accidently  changed on Dockerhub.

### ISSUE THREAD

**Issue by MadZeh** [lauwarm/docker-streamlink-recorder#19]
Hello,
thanks for the update, but you created "arm64" Tags instead of  "amd64" Tags on Dockerhub. I think this happend accidently because both are looking quite similiar.

**Comment by lauwarm** [comment]
Hey @MadZeh,

thank you for letting me know . Yeah, I kinda forgot to set the right platform.

It should be fixed now.
