### ISSUE TITLE
Sorry no issue, but a question

### ISSUE THREAD

**Issue by daniel89fhem** [lauwarm/docker-streamlink-recorder#2]
Hi lauwarm,

Ich glaube, dass du deutsch sprichst, daher schreibe ich zuerst in deutsch. 

Ich habe gestern dein docker Image installiert und einen stream eingerichtet. Da der User auf twitch gerade online war, startete sofort die Aufnahme. Daher glaubte ich, dass eh alles funktioniert. Nachdem der Streamer seinen livestream beendet hatte, wurde auch die Aufnahme beendet. Soweit so gut. 
Heute hat der Streamer wieder einen livestream gemacht. Leider wurde dieser aber nicht aufgezeichnet. Ist das so gewollt? Also dass der Stream nur aufgenommen wird, wenn man den container startet während der Streamer online ist und dann aufgenommen wird? Das regelmäßige checken ob er noch online ist, ist nur für das beenden der Aufnahme gedacht? Oder sich zum starten? Wenn zweiteres, was mache ich falsch? 

Hi, now in english.
I installed your Image yesterday. I created it with a link to a Streamer, which was at this time in a live stream. The Container records the stream. As soon as the Streamer finished his live stream, the Container stopps the recording. Thats good. 
Today the Streamer did a new live stream, but the Container didn't recorded it. Is it my mistake? Or is the Container only able to automatically finish the recording, but i have to Start it, if a new live stream starts?

**Comment by evandozier** [comment]
I'd noticed this and been meaning to open an issue and fix. It doesn't
start because the timestamp only updates once at image start time. It tries
to write the same file again unless you restart the image to refresh the
timestamp

**Comment by lauwarm** [comment]
@daniel89fhem @evandozier Hey, the container should check every 60 seconds if the stream is online and if so start the download... 
I changed a few things which are reflected in the branch "python3.8.1_buster_1.3.1", but I never got back around to merge it back to master.
The naming of the branch is a bit convoluted (python in the name; calls a bash script), but maybe you could try it out to see if it fixes the issue.

Anyways, Thank you for reporting the Problem.

@daniel89fhem Anbei ja, ich spreche auch deutsch. Sollte es noch Probleme geben kannst du die gerne in Deutsch schreiben. Ich antworte trotzdem generell in Englisch damit die anderen auch an der Diskussion teilhaben können.

**Comment by daniel89fhem** [comment]
@lauwarm @evandozier thank you to both for answering.

@evandozier how can we refresh the timestamp in the python Script?
@lauwarm ok, so you didn't use the Master Branch anymore? 

For your Information - i built my own Image, but with your dockerfile and with your python Script. I had to built it because I'm using it on a raspberry. 

So to fix this issue, we have to change the python script. Im Not so good in python scripting, so i have to spent some time in it. But maybe you can help me in this case?

**Comment by daniel89fhem** [comment]
Maybe this help us to solve the issue? https://github.com/liofal/streamlink/blob/master/streamlink-recorder.py

**Comment by lauwarm** [comment]
>  @lauwarm ok, so you didn't use the Master Branch anymore?

@daniel89fhem correct, i am currently using the Branch _python3.8.1_buster_1.3.1_.

Also to clarify, the Branch _python3.8.1_buster_1.3.1_ doesn't use the python script anymore. I switched to a bash script.

If you are building it yourself, switch to Branch _python3.8.1_buster_1.3.1_ and use the Dockerfile and streamlink-recorder.sh script instead of the python script. Those have been updated 5 months ago, instead of 2 years like in the master branch.

**Comment by daniel89fhem** [comment]
@lauwarm. Ok thank you for your Information.
I will try it. 

The docker run command is the same as of the Master branch?

**Comment by lauwarm** [comment]
@daniel89fhem Yes, it should be the same.

**Comment by daniel89fhem** [comment]
@lauwarm thank you. My raspberr image with your docker file is working fine. Thank you so much. At the moment i have 12 container running on my raspberry :)

**Comment by lauwarm** [comment]
@daniel89fhem Glad to hear that it's working fine now :+1:
