### ISSUE TITLE
Old API

### ISSUE THREAD

**Issue by Tsumitsuki** [lauwarm/docker-streamlink-recorder#4]
Heute habe ich deinen Docker unter unRaid installiert. Soweit scheint auch alles richtig zu sein, allerdings schlägt die Authentifizierung Fehl. Vermutet wird eine Veraltete Version von Streamlink die noch die Alte API von Twitch nutzt.

Werde gleich mal versuchen das manuell irgendwie zu updaten, aber ich bin neu was sowas angeht.
Von Haus aus integriert wäre also wünschenswert. ^^

Thread im unRaid Forum: https://forums.unraid.net/topic/98395-twitch-recorder-dockerapp/

PS: Bevor ich mich vertue und nichts mehr verständlich ist scheibe ich mal auf Deutsch.
Mein Englisch ist etwas eingerostet und du kannst scheinbar Deutsch. :D

**Comment by lauwarm** [comment]
Hey @Tsumitsuki 

Danke dir für die Anfrage. Wenn eure Vermutung stimmt, dass die Version von streamlink zu alt ist, sollte es recht simpel sein das zu fixen.

Ich werde dazu später mal nen Branch öffnen. Den könntest du dann ausprobieren ob damit die Authentifizierung funktioniert.

PS: Klar kannst du auf Deutsch anfragen.

**Comment by lauwarm** [comment]
Hey @Tsumitsuki 

docker pull lauwarm/streamlink-recorder:python3.8.1_buster_1.7

Probier's mal damit aus.

**Comment by Tsumitsuki** [comment]
Scheint zu funktionieren. 
Der Neue sagt zumindest "Opening Stream", wärend der alte Container noch Fehler ausspuckt.

Danach passiert allerdings nichts mehr. Meine Leitung ist aktuell aber auch Tot.
5k Down. 0,1k Up. Ping 800+ ¯\_(ツ)_/¯
Melde mich Morgen nochmal wenn mein Anschluss hoffentlich wieder läuft!

**Comment by Tsumitsuki** [comment]
Der Anschluss ist wieder online und das Token scheint auch zu funktionieren.
Habe als Tests mal Gronkhs 24/7 Kanal genommen.

Vollständiger Log:
`[cli][info] streamlink is running as root! Be careful!
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/gronkhtv
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)`

Eine Datei taucht im Zielverzeichnis allerdings nicht auf. Übersehe ich irgendetwas offensichtliches?

unRaid Docker-Settings:
![image](https://user-images.githubusercontent.com/32206990/97774578-45adf600-1b59-11eb-892d-9f4ce80d0b47.png)
![image](https://user-images.githubusercontent.com/32206990/97774585-637b5b00-1b59-11eb-970d-fd06106e1607.png)

**Comment by lauwarm** [comment]
Hey,

deine Settings in unRaid schauen in Ordnung aus.
Hab's gerade mal kurz getestet mit dem selben Stream und bei mir wird auch nichts aufgezeichnet. 
Ich werd später mal schauen wieso es Probleme macht.

**Comment by Tsumitsuki** [comment]
Sry das ich mich jetzt erst Melde. Hatte gut eine Woche kein Internet. :/

Habe heute noch mal etwas mit den Settings rumprobiert, allerdings ohne Erfolg.
Den Stream erkennt er immer noch, aber schreibt keine Datei ins Verzeichnis

**Comment by lauwarm** [comment]
Hey,

leider hab ich es bisher noch nicht gefixt.

Bezüglich OAuth Token:

https://github.com/streamlink/streamlink/issues/2680
>Also, since there's no definitive way of determining the origin of an OAuth token (Twitch's website or a third party application), the authentication data had to be removed when requesting a streaming access token. This means that with these changes, trying to log in to your Twitch account with Streamlink 1.3.0 won't do anything except logging your user name to the output. While watching streams with your provided OAuth token, you won't be able to receive in-game item drops anymore (if you've linked any games on the Twitch website to your account) and you also won't be able to access restricted streams/VODs anymore. We didn't remove the --twitch-oauth-token and --twitch-oauth-authenticate parameters though, as we didn't want to introduce breaking changes, so please be aware of that.

https://github.com/streamlink/streamlink/releases/tag/1.4.0
>Removed: Twitch auth logic, --twitch-oauth-token, --twitch-oauth-authenticate, --twitch-cookie (#2846)

https://streamlink.github.io/cli.html#command-line-usage

Das behebt nicht das Problem, dass Streams garnicht mehr gespeichert werden, aber zumindest wissen wir nun das OAuth nicht funktionieren wird.

Sobald ich mehr weiß, wieso die Streams nicht mehr gespeichert werden, melde ich mich nochmal.

**Comment by Tsumitsuki** [comment]
Ah super. Gut zu wissen.
Twitch bastelt wohl zur Zeit viel hinter den Kulissen rum.

**Comment by lauwarm** [comment]
Hey,

ich schein das Problem gefunden zu haben.
Ich hab die Readme nicht angepasst gehabt. Dementsprechend steht dort aktuell noch drin das die Files unter '/download' gespeichert werden. Die werden aber unter '/home/download' gespeichert.
Probier mal aus es unter /home/download/ zu mounten. 

Habe zusätzlich noch nen neuen Branch erstellt (python3.9.0_buster_1.7), welcher von Docker Hub gerade geprüft wird.

Wenns weiterhin Probleme gib meld dich einfach.

Ansonsten noch ein schönes Wochenende.

**Comment by Tsumitsuki** [comment]
ja Nice! Scheint alles zu Funktionieren!
Zwei Streams zeichnet er zumindest gerade auf.

Aus irgend einem Grund hängt beim VLC der Ton und bei WMP das Bild.
Im power DVD läuft alles flüssig!
Liegt also wohl an den Playern.

Tausend dank!

**Comment by lauwarm** [comment]
Hey,

freut mich zu hören. :+1: 

Das der Ton Probleme macht ist seltsam. Hatte nur kurz nen Stream getestet und mit MPV wiedergegeben. Da schien es zu funktionieren. Könnte vielleicht nen Problem durch die Art wie Twitch Werbung einbettet sein. Da wird wohl die Werbung direkt in den HLS stream eingefügt. Genau weiß ich es jedoch nicht. 

Werde dann die Tage noch die Änderungen wieder in master mergen.

Bis dahin.
