### ISSUE TITLE
Passing in OAuth Token

### ISSUE THREAD

**Issue by HumboShot** [lauwarm/docker-streamlink-recorder#44]
When i try to run the container with the --twitch-api-header stream option, it fails, and gives the the fail messages of 
`streamlink: error: unrecognized arguments: best`

The options i pass in look like this
`--twitch-disable-hosting --twitch-api-header=Authorization=OAuth MyOAuthTokenHere`

Any idea of what i am doing wrong?

**Comment by lauwarm** [comment]
Hello @HumboShot,

https://streamlink.github.io/cli.html#cmdoption-twitch-api-header

Maybe you could try to run it like this:
 
```-e streamOptions='--twitch-disable-hosting --twitch-api-header OAuth=MyOAuthTokenHere'```

I personally am not subbed to a Channel to test out if Ads would get filtered out. Maybe you could report back if it is working as intended.

**Comment by HumboShot** [comment]
From the quick testing i have done, this seems like it is working
