### ISSUE TITLE
chaturbate plugin not working

### ISSUE THREAD

**Issue by Nach0-Stallion** [lauwarm/docker-streamlink-recorder#6]
Hi, I have recently discovered your docker and it was exactly what i was looking for, so i have set ot up on my unraid server and for twitch it seems to be recording fine, however accessing chaturbate streams gives an error that no plugin is available to handle the stream, even though the plugin is installed into the plugins folder as part of the install.
is there some additional option i need to active to get it to function.. 
any help greatly appreciated..

[cli][info] streamlink is running as root! Be careful!
error: No plugin can handle URL: www.chaturbate.com/

**Comment by lauwarm** [comment]
Hi,

it's currently not mentioned in the README but you need to specify the "plugin-dir":
`-e streamOptions='--plugin-dirs=/home/plugins/'`

The complete cli command should look _something_ like this:
`$ docker run -v /home/:/home/download -e streamLink='twitch.tv/twitch' -e streamQuality='best' -e streamName='twitch' -e streamOptions='--plugin-dirs=/home/plugins/' lauwarm/streamlink-recorder`

**Comment by Nach0-Stallion** [comment]
This is perfect, thank you for this, I'm all up and running now.

**Comment by lauwarm** [comment]
Glad to hear that it's working. 👍
