### ISSUE TITLE
Request to change path of the script

### ISSUE THREAD

**Issue by MadZeh** [lauwarm/docker-streamlink-recorder#7]
Hi, is it maybe possible to move the "streamlink-recorder.sh"-script from "/home" to "/home/script" or similar to give the possibility for access from the docker-host? 
Reason is that I'm using Unraid and want to edit the script to my needs. If I would know how to build a container by myself, I would do it by myself. Thanks a lot.

**Comment by lauwarm** [comment]
Hey,

I created a Branch 'script-folder'. The Script has been moved to `/home/script/`. You should be able to pull this Docker Image and edit the Script to your needs.

To get the Branch just do a docker run as normal but specify the Tag `lauwarm/streamlink-recorder:script-folder`.

I Personally don't own a Unraid System. Could you explain why you are not able to mount the /home Folder? Shouldn't you be able to just do a `-v /path/on/your/unraid:/home` and get access to the script?

**Comment by MadZeh** [comment]
Hi Lauwarm, 
Vielen Dank für den Branch. Also, es liegt nicht daran, dass ich `/home` nicht auf Unraid zu `/mnt/user/appdata/streamlink-recorder` mounten kann , sondern dass `/home/download` ein Unterverzeichnis von `/home` ist, allerdings unter Unraid strukturell in ein ganz anderes Verzeichnis gehört. Sprich, ich wollte nur eine saubere Trennung von Script und Downloads haben.

**Comment by lauwarm** [comment]
Hey,

danke für die Erläuterung. 
Werde es dann die Tage in master mergen.
