### ISSUE TITLE
 ([Errno 13] Permission denied:

### ISSUE THREAD

**Issue by Odimeae** [lauwarm/docker-streamlink-recorder#82]
Log: 

UID : 1000 
GID : 1000
[cli][info] Found matching plugin twitch for URL twitch.tv/stream
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[cli][info] Writing output to
/home/download/stream-20231027-032017.mkv
**error: Failed to open output: /home/download/stream-20231027-032017.mkv ([Errno 13] Permission denied: '/home/download/stream-20231027-032017.mkv')**
[cli][info] Closing currently open stream...

```
docker run
  -d
  --name='twitcher'
  --net='bridge'
  -e TZ="Europe/London"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="homeserver"
  -e HOST_CONTAINERNAME="twitcher"
  -e 'streamLink'='twitch.tv/stream'
  -e 'streamQuality'='best'
  -e 'streamName'='stream'
  -e 'streamOptions'='--twitch-disable-reruns'
  -e 'uid'='1000'
  -e 'gid'='1000'
  -l net.unraid.docker.managed=dockerman
  -v '/mnt/user/downloads/streams/twitch/':'/home/vod':'rw' 'lauwarm/streamlink-recorder
```

**Comment by lauwarm** [comment]
Hey @Odimeae

This problem seems like a duplicate of #16.

There seems to be a problem with _ID 1000_. Why that is I do not know at this time.

Once I have more information I will let you know.

**Comment by ijrood** [comment]
Hello there,
had the same issue, only way I found to make it work was to set id root(not that great)
