### ISSUE TITLE
add UID and GID

### ISSUE THREAD

**Issue by lauwarm** [lauwarm/docker-streamlink-recorder#9]
ability to set uid and gid

**Comment by lauwarm** [comment]
Hello everyone,

I created a Branch called `userid` which uses a entrypoint Script to switch UserID and GroupID.
With this change streamlink should stop running as root. 

Given that the right permission is set for the download folder, it seems to work.
I still would appreciate if someone would provide additional feedback.

Greetings,
lauwarm

**Comment by Nach0-Stallion** [comment]
im happy to try this out if you can advise how i install this version? :/

**Comment by lauwarm** [comment]
You can specify the Tag which you want to use.
To test it out you would use the `userid` Tag.

```
$ docker run -v /home/:/home/download -e streamLink='twitch.tv/twitch' -e streamQuality='best' -e streamName='twitch' -e streamOptions='--twitch-disable-hosting' -e uid='1001' -e gid='1001' lauwarm/streamlink-recorder:userid
```

**Comment by lauwarm** [comment]
Alright,
I've been testing it with a Twitch and Youtube stream the past couple days and it seems to work fine.
The created files have the right permission on my NAS.
